### ISSUE TITLE
installation problem...

### ISSUE THREAD

**Issue by Suspectxyzz** [meanwhiletothestars/CS2_DMA_Radar#1]
I installed python 3 and I get this error on windows v 22h2
![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/5c499afa-f4e6-46b0-aa4e-08a546307516)

and there is another problem
* Start in match with /python main.py   `main.py` does not exist in your project is `app.py` ?
* and you can try to add readtldr.gg/simpleradar

**Comment by therewillwhile** [comment]
hello, struct is default package of python 3, so pip can't find it. Updated requirements.txt

yeah, start with app.py. Updated readme

I'll take a look about readtldr.gg/simpleradar

**Comment by Suspectxyzz** [comment]
fixed

**Comment by Suspectxyzz** [comment]
I solved everything but it's missing.

* maps : Dust2, Office 
* make a color different from your team for confusion or you can choose numbers / names
* websocket (as I said above, the laptop with dma is stupid, I had to pay attention to the match and to him :) )

One more question, does this project work on ubuntu server? or only on the gui version?

edit bug dma : I played a few premier matches and the dma radar showed only 4 people in the opposing team
@meanwhiletothestars

**Comment by therewillwhile** [comment]
1. i'll add Dust2 and Office
2. it will be config where u be able to set up names and other things. i like the mate colours, but for now i dont know how to read teammate colors
3. i never worked with websocket technology, but it is the logical continuation of radar
4. for now u need to use os with graphics, so ubuntu server will not work. if i add websocket it ofcourse will work with ubuntu server

**Comment by therewillwhile** [comment]
I have big plans for this project, but right now I don't have much time to actively work on it. so far, it's working and showing entity. I found a lot of bugs, but for now I want to transfer the technology to the websocket and read who is carrying the bomb and the colors of the teammates (I did not find this information anywhere on forums)
