### ISSUE TITLE
maps   no   de_dust2  ?

### ISSUE THREAD

**Issue by HH333** [meanwhiletothestars/CS2_DMA_Radar#10]
maps   no   de_dust2 ?

**Comment by Suspectxyzz** [comment]
![default](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/926d4554-4def-487b-a790-13c2d63146a2)
![radar](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/a050cb49-a5a8-4ef8-8d1f-8a1b66bcc71f)
[meta.json](https://github.com/meanwhiletothestars/CS2_DMA_Radar/files/14241521/meta.json)

**Comment by therewillwhile** [comment]
If your offset work, I'll add it
