### ISSUE TITLE
request for adding the map/s!

### ISSUE THREAD

**Issue by Suspectxyzz** [meanwhiletothestars/CS2_DMA_Radar#11]
[meta.json](https://github.com/meanwhiletothestars/CS2_DMA_Radar/files/14241530/meta.json)
![radar](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/2c2ae957-c24e-4dec-8335-4ccd60ab682d)
[de_dust2.txt](https://github.com/meanwhiletothestars/CS2_DMA_Radar/files/14241537/de_dust2.txt)
[cs2_maps_[unknowncheats.me]_.zip](https://github.com/meanwhiletothestars/CS2_DMA_Radar/files/14241540/cs2_maps_.unknowncheats.me._.zip)

**Comment by HH333** [comment]
maps no de_dust2

**Comment by therewillwhile** [comment]
I will add
