### ISSUE TITLE
everyone's favorite map :)

### ISSUE THREAD

**Issue by Suspectxyzz** [meanwhiletothestars/CS2_DMA_Radar#18]
I wanted to ask if you can stop the program from automatically closing when the map is no longer there  (it's annoying, I keep reopening the application)
and if you can update, describe for beginners
if you can add a time when bmb explodes?
https://github.com/meanwhiletothestars/CS2_DMA_Radar/pull/13/commits/8f8c49646bb38843d08cc4ae161c31de303a4513

![IMG_2637](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/71bafebe-08f0-4a73-a364-b49ca4e939e4)

[de_dust2.zip](https://github.com/meanwhiletothestars/CS2_DMA_Radar/files/14387575/de_dust2.zip)

**Comment by therewillwhile** [comment]
added all except bomb, thanks!
