### ISSUE TITLE
de_office

### ISSUE THREAD

**Issue by patt1** [meanwhiletothestars/CS2_DMA_Radar#19]
Thx for publishing the project.
websocket radar would be nice.

de_office (not perfect):
[meta.json](https://github.com/meanwhiletothestars/CS2_DMA_Radar/files/14389417/meta.json)
![radar](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/11842720/63134c75-ebfd-46f4-9198-df3918d52e40)
keep up the great work!

**Comment by therewillwhile** [comment]
added, thank you!
