### ISSUE TITLE
can u updata maps and Increase perspective following. It would be even better if it could be displayed on a webpage and mapped to the internal network

### ISSUE THREAD

**Issue by Esingpawn** [meanwhiletothestars/CS2_DMA_Radar#2]
![cs_italy_radar_psd](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/57138070/762c20f1-77f7-46ce-82a3-7a15fa4ab510)
![cs_office_radar_psd](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/57138070/c21e4066-db51-4361-b104-30a9a360b9a3)
![de_ancient_radar_psd](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/57138070/fefa5a50-b33d-427c-bb7f-6aab9d5fb024)
![de_anubis_radar_psd](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/57138070/8d17af5a-9585-4f96-a447-ddf98beee495)
![de_dust2_radar_psd](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/57138070/b899d6f3-e194-43f4-b542-8bedec38096f)
![de_inferno_radar_psd](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/57138070/f96f425a-dce0-44f2-b2eb-cabd7253fa8c)
![de_nuke_lower_radar_psd](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/57138070/021868d7-73a6-4f5f-9cca-d76a3aba4449)
![de_nuke_radar_psd](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/57138070/cee5d509-9335-479a-ac34-7999a6a31954)
![de_overpass_radar_psd](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/57138070/ad01409c-769f-48b4-b587-db6e8efa9eac)
![de_vertigo_lower_radar_psd](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/57138070/93f42192-7a83-4d27-83cd-f2c04661cbde)
![de_vertigo_radar_psd](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/57138070/4ff9dde7-2bf7-46df-a7cc-1e9b520e283f)
![radar](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/57138070/c2378a26-11da-4510-8f4e-2fba87d2f71b)

**Comment by Esingpawn** [comment]
How do I want to donate to you

**Comment by therewillwhile** [comment]
dont donate me) i didnt make something cool. 

someday i will add folowing, websocket and other shit, but i need to work on my real job. so it will take like 1 month or more
