### ISSUE TITLE
how to donate

### ISSUE THREAD

**Issue by mn2xujiakun** [meanwhiletothestars/CS2_DMA_Radar#21]
U deserves the donations bro

**Comment by therewillwhile** [comment]
i live in Russia, so i have no paypal like wallets. i think that guys, who want to donate me didnt have crypto wallets. so dont donate me) this program is free(i made it for myself and just make repository public)

**Comment by HH333** [comment]
The latest version, the software cannot run properly and crashes.

**Comment by therewillwhile** [comment]
> The latest version, the software cannot run properly and crashes.

can u provide screenshots/console logs please? probably incorrect install software/dma problem

**Comment by patt1** [comment]
> i live in Russia, so i have no paypal like wallets. i think that guys, who want to donate me didnt have crypto wallets. so dont donate me) this program is free(i made it for myself and just make repository public)

replace the picture in: maps/empty with your bitcoin qr-code for people who wanna donate.

**Comment by therewillwhile** [comment]
maybe, i will add qr somewhere after websocket version release, thx

**Comment by mn2xujiakun** [comment]
> maybe, i will add qr somewhere after websocket version release, thx

Also add up ETH, LTC, and USDT  :) so that I can donate

**Comment by therewillwhile** [comment]
added my wallets to the bottom of readme. thanks all!
