### ISSUE TITLE
[bug issues] only can be see self radar 

### ISSUE THREAD

**Issue by NaCoLiu** [meanwhiletothestars/CS2_DMA_Radar#23]
![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/42311502/94a71b75-e0c6-46ba-b679-a894a3812308)

**Comment by Suspectxyzz** [comment]
![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/4e9b963a-331e-4d5b-a067-7da9c82a8d51)
it works well for me now I tested it (mm )
restart second pc
