### ISSUE TITLE
Program compilation error

### ISSUE THREAD

**Issue by Hsupering** [meanwhiletothestars/CS2_DMA_Radar#25]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\CS2_DMA_Radar-main\app.py", line 203, in <module>
    entity_id = struct.unpack("<Q", cs2.memory.read(EntityPawnListEntry + 0x78 * (Pawn & 0x1FF), 8, memprocfs.FLAG_NOCACHE))[0]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 8 bytes

**Comment by Suspectxyzz** [comment]
@Hsupering 
I can confirm it does not work if you download directly so download from here
1.5.2 / 1.5.1
https://github.com/meanwhiletothestars/CS2_DMA_Radar/releases

**Comment by meanwhiletothestars** [comment]
bro just use release page

**Comment by Suspectxyzz** [comment]
@meanwhiletothestars close :>>???
