### ISSUE TITLE
Radar1.6 version has bugs. The character radar position is wrong after zooming in on the map.

### ISSUE THREAD

**Issue by HH333** [meanwhiletothestars/CS2_DMA_Radar#26]
Radar1.6 version has bugs. The character radar position is wrong after zooming in on the map.

**Comment by Suspectxyzz** [comment]
I still have some problems :) there is no point in opening a new topic :0
and what's more important

1. with the disconnection of the players, if 1 leaves the game, the whole team no longer appears, or in the worst cases, only 1 appears [it does not help to restart the PC / restart the radar]
2. I can't close the program with ctrl+c, I have to end task every time...  [this problem has been noticed for a long time]
4. this update, as you can see in the picture, does not know all the weapons, it only knows a few weapons and nade(he knows them all) 
3. pwp <3



![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/e5ead7b9-ee42-482e-a204-1e1abf0e51ec)
![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/171ae9b2-154e-4537-91c5-63412d5f43cd)  if you can make it move in the direction you want, like +90 degrees

**Comment by xiaticc1** [comment]
Hello I'm from China I can't directly access the github site in China I see that your offset is directly from the git web page so I can't use it directly I need to open a vpn every time Can there be a version that 1.6 does not update automatically Thank you

**Comment by therewillwhile** [comment]
> Hello I'm from China I can't directly access the github site in China I see that your offset is directly from the git web page so I can't use it directly I need to open a vpn every time Can there be a version that 1.6 does not update automatically Thank you

added

**Comment by therewillwhile** [comment]
> I still have some problems :) there is no point in opening a new topic :0 and what's more important
> 
> 1. with the disconnection of the players, if 1 leaves the game, the whole team no longer appears, or in the worst cases, only 1 appears [it does not help to restart the PC / restart the radar]
> 2. I can't close the program with ctrl+c, I have to end task every time...  [this problem has been noticed for a long time]
> 3. this update, as you can see in the picture, does not know all the weapons, it only knows a few weapons and nade(he knows them all)
> 4. pwp <3
> 
> ![image](https://private-user-images.githubusercontent.com/45514952/313286824-e5ead7b9-ee42-482e-a204-1e1abf0e51ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTQ5MzksIm5iZiI6MTcxMDc5NDYzOSwicGF0aCI6Ii80NTUxNDk1Mi8zMTMyODY4MjQtZTVlYWQ3YjktZWU0Mi00ODJlLWEyMDQtMWUxYWJmMGU1MWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDIwNDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZDc5Mzg5OWRlOGY5ZGRlNmRjNWNlMmJhYjRkZmNiMTFjMGQwZTA1YzYzOTI5NWNiNWM2ZDIxMzg3OWIwNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RVe6kFbVo9WmBu61j40egMmGZyYkUSvQeQltXEFuZno) ![image](https://private-user-images.githubusercontent.com/45514952/313403107-171ae9b2-154e-4537-91c5-63412d5f43cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTQ5MzksIm5iZiI6MTcxMDc5NDYzOSwicGF0aCI6Ii80NTUxNDk1Mi8zMTM0MDMxMDctMTcxYWU5YjItMTU0ZS00NTM3LTkxYzUtNjM0MTJkNWY0M2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDIwNDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMTMwMGM3MDg0ODkzZmNjZjY1MmI4MGIyMzE2ZGRkMTViMjExZGVkYjljYzQxOGE3ZTU4YWQ5YjJkZGU0OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p0loURu3yWGmDu6r1_wlZe1rJt3ts1RUJz6EmViTxYI) if you can make it move in the direction you want, like +90 degrees

fixed all except weapon id cuz it take a long time to find weapon id's for all weapons
