### ISSUE TITLE
c4 position 

### ISSUE THREAD

**Issue by quadrat75** [meanwhiletothestars/CS2_DMA_Radar#28]
Привет!
А реально ли добавить на карту выпавшую бомбу ? Это когда терроры её скидывают, либо она выпадает при убийстве тера

**Comment by therewillwhile** [comment]
все реально. просто нужно найти способ как это читать. кто то когда то на форуме мне писал как это сделать, но я пробовал и у меня не получилось. может как нибудь попробую еще
