### ISSUE TITLE
web-based Is it in an incomplete state?

### ISSUE THREAD

**Issue by Heaven38** [meanwhiletothestars/CS2_DMA_Radar#29]
I come from China, so my English is not very good
Pygame radar is very effective for me. But it cannot be conveniently shared with my teammates. My teammates usually need to open a software frequently to watch it.So I plan to use web based 
The operation went smoothly, but when I opened 127.0.0.1:5000, I started reporting errors

**Comment by Heaven38** [comment]
![89b1293437b3958d334c93484186638](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/80700659/afb24fec-de9d-47eb-995c-4dc3e4c5b972)
![86477ad64dcdb4c89f7064b1b4227f1](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/80700659/ee3408a8-e6e8-425b-96d6-4e027525d412)
Error as above

**Comment by therewillwhile** [comment]
web based not worked for now. will be later

**Comment by Heaven38** [comment]
> 基于网络的暂时不起作用。稍后会

Thank you for your prompt reply. I will be patient and wait. Thank you

**Comment by Heaven38** [comment]
> web based not worked for now. will be later

There is one more question The battle platform I am using has been updated tonight, causing the software to be unable to find the program. What should I do?
![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/80700659/3c2df37d-6faf-4aef-a2d4-111fc3ed4470)

**Comment by therewillwhile** [comment]
i have same problem on amd processors(if u using it, turn off IOMMU) and there is another bios option need to turn off (idk what is it)

on intel u need to turn off vt-d and virtualization

**Comment by Heaven38** [comment]
> i have same problem on amd processors(if u using it, turn off IOMMU) and there is another bios option need to turn off (idk what is it)
> 
> on intel u need to turn off vt-d and virtualization

I tried to turn off virtualization but still couldn't find the program
It should be caused by the platform's anti cheating, because I can use it normally on the official server

**Comment by therewillwhile** [comment]
so, this is dma firmware problem.

https://github.com/Silverr12/DMA-CFW-Guide
this guide probably will help u, or probably not.

u can buy dma firmware for valorant. (vanguard isolating game memory from other devices. i think ur anticheat does same thing)
