### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Fasdxx** [meanwhiletothestars/CS2_DMA_Radar#30]
I am a beginner, how should I solve this

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\cs3\venv\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\cs3\app.py", line 29, in <module>
    offsets = get('https://raw.githubusercontent.com/a2x/cs2-dumper/main/generated/offsets.json').json()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\cs3\venv\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 4 (char 3)

**Comment by Suspectxyzz** [comment]
> I am a beginner, how should I solve this
> 
> Traceback (most recent call last): File "C:\Users\Administrator\Desktop\cs3\venv\Lib\site-packages\requests\models.py", line 971, in json return complexjson.loads(self.text, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 340, in decode raise JSONDecodeError("Extra data", s, end) json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\Administrator\Desktop\cs3\app.py", line 29, in offsets = get('https://raw.githubusercontent.com/a2x/cs2-dumper/main/generated/offsets.json').json() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\Desktop\cs3\venv\Lib\site-packages\requests\models.py", line 975, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Extra data: line 1 column 4 (char 3)

I also tested it now and the creator that generates the offset has changed several things now and it no longer works

**Comment by therewillwhile** [comment]
> I am a beginner, how should I solve this
> 
> Traceback (most recent call last): File "C:\Users\Administrator\Desktop\cs3\venv\Lib\site-packages\requests\models.py", line 971, in json return complexjson.loads(self.text, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 340, in decode raise JSONDecodeError("Extra data", s, end) json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\Administrator\Desktop\cs3\app.py", line 29, in offsets = get('https://raw.githubusercontent.com/a2x/cs2-dumper/main/generated/offsets.json').json() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\Desktop\cs3\venv\Lib\site-packages\requests\models.py", line 975, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Extra data: line 1 column 4 (char 3)

u do it right way, but https://github.com/a2x/cs2-dumper deleted offsets from his github page. u can switch to internal offsets in config use "update_offsets": 0,

**Comment by Fasdxx** [comment]
> > 我是初学者，我该如何解决这个问题
> > 回溯（最近一次调用最后）：文件“C：\ Users \ Administrator \ Desktop \ cs3 \ venv \ Lib \ site-packages \ requests \ models.py”，第971行，在json中返回complexjson.loads（self.text， **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 文件 "C:\Users\Administrator \AppData\Local\Programs\Python\Python312\Lib\json__init__.py"，第 346 行，加载中返回 _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^ ^^^^^^ 文件“C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py”，第 340 行，在解码中引发 JSONDecodeError(“额外数据”, s, end ) json.decoder.JSONDecodeError: 额外数据：第 1 行第 4 列（字符 3）
> > 在处理上述异常的过程中，又出现了一个异常：
> > 回溯（最近一次调用最后一次）：文件“C:\Users\Administrator\Desktop\cs3\app.py”，第 29 行，offsets = get(' [https://raw.githubusercontent.com/a2x/cs2-dumper /main/ generated/offsets.json').json(](https://raw.githubusercontent.com/a2x/cs2-dumper/main/generated/offsets.json').json() ) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^ 文件“C:\Users\Administrator\Desktop\cs3\venv\Lib\site-packages\requests\models.py”，第 975 行，json 引发 RequestsJSONDecodeError(e.msg, e.doc, e. pos) requests.exceptions.JSONDecodeError：额外数据：第 1 行第 4 列（字符 3）
> 
> 你的做法是正确的，但是https://github.com/a2x/cs2-dumper从他的 github 页面中删除了偏移量。您可以使用“update_offsets”切换到配置中的内部偏移量：0，

Thank you very much for your help. The problem is solved, which means that future updates will not be automatically obtained, right?

**Comment by Fasdxx** [comment]
update_offsets": 0, but there will be players that are not displayed when using it

**Comment by Suspectxyzz** [comment]
> update_offsets": 0, but there will be players that are not displayed when using it

    offsets = get('https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/win/offsets.json').json()
    clientdll = get('https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/win/client.dll.json').json()
    @meanwhiletothestars close !
