### ISSUE TITLE
Hello, the software can no longer be used normally and needs to be updated.

### ISSUE THREAD

**Issue by HH333** [meanwhiletothestars/CS2_DMA_Radar#31]
Hello, the software can no longer be used normally and needs to be updated.

**Comment by therewillwhile** [comment]
https://github.com/a2x/cs2-dumper deleted offsets from his github page. u can switch to internal offsets in config use "update_offsets": 0,

**Comment by Suspectxyzz** [comment]
@HH333 
    offsets = get('https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/win/offsets.json').json()
    clientdll = get('https://raw.githubusercontent.com/a2x/cs2-dumper/main/output/win/client.dll.json').json()
    @meanwhiletothestars  close !
