### ISSUE TITLE
help

### ISSUE THREAD

**Issue by xiaticc1** [meanwhiletothestars/CS2_DMA_Radar#33]
Hello, I get this error when using your radar in 5e RuntimeError: Process.module(): Failed. {It's a platform like Faceit}

**Comment by therewillwhile** [comment]
1. anticheat isoladed dma or u need another windows(like 21h2) - it can be a problem too

**Comment by Heaven38** [comment]
5e has updated its anti cheating feature, isolating memory from other devices (perhaps?), and I have been trying to solve it recently

**Comment by therewillwhile** [comment]
valorant made the same thing. u need custom firmware for this. module not found error in anyway indicates isolating memory(from windows, anticheat or bios settings)
