### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Fasdxx** [meanwhiletothestars/CS2_DMA_Radar#34]
Hello, why do I encounter incomplete loading of enemies during use?
update_offsets: 1

**Comment by therewillwhile** [comment]
what is incomplete player loading? if it less than need to be --> increase max_clients in config

**Comment by HH333** [comment]
> what is incomplete player loading? if it less than need to be --> increase max_clients in config

I also encountered the same problem. Sometimes there are only 3 people or 4 enemies on the radar. Sometimes there is 1 less teammate and 2 less enemies on the radar. A total of 8 radars appear.

**Comment by HH333** [comment]
max_clients   10

**Comment by therewillwhile** [comment]
try more max clients.
