### ISSUE TITLE
CSGO has been updated and the software is invalid. Please update it.

### ISSUE THREAD

**Issue by HH333** [meanwhiletothestars/CS2_DMA_Radar#35]
CSGO has been updated and the software is invalid. Please update it.

**Comment by therewillwhile** [comment]
https://github.com/a2x/cs2-dumper/tree/main/output

**Comment by HH333** [comment]
> https://github.com/a2x/cs2-dumper/tree/main/output

update_offsets: 1  /   The software will crash and the software cannot be used normally.

update_offsets: 0   /   can be used successfully

**Comment by Suspectxyzz** [comment]
![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/14573085-f8d3-4dae-95df-54398b987508)

**Comment by therewillwhile** [comment]
> > https://github.com/a2x/cs2-dumper/tree/main/output
> 
> update_offsets: 1 / The software will crash and the software cannot be used normally.
> 
> update_offsets: 0 / can be used successfully

bro in newer version this setting are not working lol.

**Comment by Suspectxyzz** [comment]
> > > https://github.com/a2x/cs2-dumper/tree/main/output
> > 
> > 
> > update_offsets: 1 / The software will crash and the software cannot be used normally.
> > update_offsets: 0 / can be used successfully
> 
> bro in newer version this setting are not working lol.

after a few searches I found the problem and for me it is again cs2-dumper does not update

**Comment by therewillwhile** [comment]
for some reason it didnt patch the client.dll.json, idk

**Comment by HH333** [comment]
> > > > https://github.com/a2x/cs2-dumper/tree/main/output
> > > 
> > > 
> > > update_offsets: 1 / The software will crash and the software cannot be used normally.
> > > update_offsets: 0 / can be used successfully
> > 
> > 
> > bro in newer version this setting are not working lol.
> 
> after a few searches I found the problem and for me it is again cs2-dumper does not update

Got it, thank you very much

**Comment by HH333** [comment]
> for some reason it didnt patch the client.dll.json, idk

Got it, thank you very much

**Comment by Suspectxyzz** [comment]
@meanwhiletothestars close 👍🏻
