### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Suspectxyzz** [meanwhiletothestars/CS2_DMA_Radar#36]
I think that after the update, in which you solved the problem by closing the window, it closes randomly without errors or anything like that
or after doing alt+tab with the game
![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/c9b10af9-4186-4f22-b1ae-d751753fbcb2)
![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/195e5d57-fe0d-4ac6-89da-2236a8115cf4)
![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/b836b65d-a8fc-496f-9423-06c1d567ea83)

**Comment by therewillwhile** [comment]
idk, will see after offset update

**Comment by Suspectxyzz** [comment]
> idk, will see after offset update

are updated

**Comment by Suspectxyzz** [comment]
same bug

![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/439a3f89-8186-4740-be35-a5a50e728eda)

**Comment by therewillwhile** [comment]
idk what is it

**Comment by Suspectxyzz** [comment]
thanks for the answer though
I have another question, if you can add to the radar in the top left who is watching you ":)?
if you enter the desktop and enter the game quickly you will get this crash you have to wait 5 seconds if I don't receive it

**Comment by Suspectxyzz** [comment]
[1.6.1](https://github.com/meanwhiletothestars/CS2_DMA_Radar/releases/tag/1.6.1)   works well good the version in which he did not read all the weapons
[1.6.2.1](https://github.com/meanwhiletothestars/CS2_DMA_Radar/releases/tag/1.6.2.1)  this version, in which all the weapons were read correctly, makes the program stop working
https://github.com/meanwhiletothestars/CS2_DMA_Radar/releases/tag/1.6.3  this version works correctly, the program no longer crashes, you can use alt+tab quickly
if you still want to test the web version, you can leave me a message !
