### ISSUE TITLE
Cant load all players / cant display chinese player names

### ISSUE THREAD

**Issue by mn2xujiakun** [meanwhiletothestars/CS2_DMA_Radar#37]
Cant load all players: Have to change max clients to 50 or above to load all the players
Cant display chinese player names, name shows as squares

**Comment by Suspectxyzz** [comment]
> Cant load all players: Have to change max clients to 50 or above to load all the players Cant display chinese player names, name shows as squares

if you mean other dm/casual game modes, you really have to change it manually, but on mm it works well at the moment, I didn't tested last build
and not only for Chinese text, it works the same for several symbols

edit : for meanwhiletothestars  `in certain longer names the weapon is not visible`

**Comment by mn2xujiakun** [comment]
> > Cant load all players: Have to change max clients to 50 or above to load all the players Cant display chinese player names, name shows as squares
> 
> if you mean other dm/casual game modes, you really have to change it manually, but on mm it works well at the moment, I didn't tested last build and not only for Chinese text, it works the same for several symbols
> 
> edit : for meanwhiletothestars `in certain longer names the weapon is not visible`

Sorry, both casual and other third party platform 5v5 games can not load all players, I guess this is a problem associated with chinese player name problem?
