### ISSUE TITLE
Faceit

### ISSUE THREAD

**Issue by luminocityR** [meanwhiletothestars/CS2_DMA_Radar#38]
Hi there. Thank you for this release.
I never mained cs and dont really know about what faceit detects / checks for like memory writing etc. and therefore was wondering if it would work in faceit.

**Comment by therewillwhile** [comment]
it will, but u need to have custom dma firmare to stay undetect. it all demands on dma firmware. and it can be any soft u want( for dma)

**Comment by luminocityR** [comment]
Thanks for your response. I thought that using other cheats with view angle / pixel aimbots -even through dma - it would be detected in faceit no?

**Comment by therewillwhile** [comment]
all reading-only soft will be undetected until u have good firmware for card. for aim u need kmbox
