### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by xiaticc1** [meanwhiletothestars/CS2_DMA_Radar#41]
[+] Finded client base
[+] Entered entitylist
[+] Found map de_overpass
[+] Find 2 entitys. If it is not equal to your lobby, hit the cross to do re-search
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\手动\app.py", line 211, in <module>
    time_delta = clock.tick(60)/1000.0
                 ^^^^^^^^^^^^^^
KeyboardInterrupt
  

After today's update, it shows that this is unusable

**Comment by therewillwhile** [comment]
bro u use so old version) download latest please.

entity search was like in 1.3 version or way before
