### ISSUE TITLE
A question.

### ISSUE THREAD

**Issue by UzukiOmega** [meanwhiletothestars/CS2_DMA_Radar#42]
Does this project works on KVM?

**Comment by therewillwhile** [comment]
idk. it uses memprocfs that uses leechcorepyc. leechcore is dma software, so probably no

**Comment by UzukiOmega** [comment]
Alright, I had just see that programs that use memflow will work on KVM.

**Comment by therewillwhile** [comment]
all python external cheats use memflow

and all dma python cheats use memprocfs
