### ISSUE TITLE
Launch problems.

### ISSUE THREAD

**Issue by Suspectxyzz** [meanwhiletothestars/CS2_DMA_Radar#43]
`
python.exe .\app.py
pygame 2.5.2 (SDL 2.28.3, Python 3.12.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\~\Desktop\CS2_DMA_\app.py", line 66, in <module>
    m_bIsDefusing = clientdll['client.dll']['classes']['C_CSPlayerPawnBase']['fields']['m_bIsDefusing']
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'm_bIsDefusing'
`

A fix for those who don't know :

add to the front `#` or remove line 
311 & 66

**Comment by therewillwhile** [comment]
download new app.py. now should work
