### ISSUE TITLE
The software needs to be updated, thank you

### ISSUE THREAD

**Issue by HH333** [meanwhiletothestars/CS2_DMA_Radar#45]
After the game is updated, the software crashes when I open it. It cannot be used and needs to be updated. Thank you very much.

**Comment by Suspectxyzz** [comment]
> After the game is updated, the software crashes when I open it. It cannot be used and needs to be updated. Thank you very much.

it works well for me and I played 4-7 games today
download form this "https://github.com/meanwhiletothestars/CS2_DMA_Radar/archive/refs/heads/main.zip"
