### ISSUE TITLE
How can I get the map offsets (meta.json)

### ISSUE THREAD

**Issue by kauanF7** [meanwhiletothestars/CS2_DMA_Radar#46]
How can I get the map offsets (meta.json)? 
I saw about "offsetfinder.py" but didn't find it in the project.
Running here the only map that doesn't work correctly is overpass.

By the way, congratulations on the project

**Comment by therewillwhile** [comment]
thanks! u can find it on testing/offset_manipulator.py

this is kludge, but u can use it to find offset of any map
