### ISSUE TITLE
    from pygame import DIRECTION_LTR ImportError: cannot import name 'DIRECTION_LTR' from 'pygame' 

### ISSUE THREAD

**Issue by Cqx06177** [meanwhiletothestars/CS2_DMA_Radar#48]

**Comment by Suspectxyzz** [comment]
I have the same problem on 3 different PCs
I talked to someone who owns this project `pygame_gui` and he said that the current project is `pygame-ce`  better faster .
if you can take a look for  `pygame-ce` 
it is the same as the old one 
https://github.com/MyreMylar/pygame_gui/issues/587
@meanwhiletothestars

**Comment by Cqx06177** [comment]
Can pygame-ce replace pygame_gui directly?

**Comment by therewillwhile** [comment]
will fix soon, thx for info

**Comment by Cqx06177** [comment]
Thank you for your attention and look forward to your update

**Comment by therewillwhile** [comment]
i didn't have this issue on latest radar and python version.

**Comment by Suspectxyzz** [comment]
https://img.meowless.club/NVIDIA_Overlay_zI4JlUJ6Ia.png
i same for 3 pc differently [I think that after you have a clean system then you will have a problem] (you can upload the files from `Python\Python312\Lib\site-packages\pygame_gui`)
1 windows 11
2 windows 10 
@meanwhiletothestars

**Comment by therewillwhile** [comment]
pip install pygame-gui works, pygame_gui not

**Comment by Suspectxyzz** [comment]
> pip install pygame-gui works, pygame_gui not

ok but if i put `pygame-gui` i have this error
`
python.exe .\app.py
  File "C:\Users\FeedMyCat\Desktop\CS2_DMA_Radar-main\app.py", line 5
    import pygame-gui
                 ^
SyntaxError: invalid syntax`

if I change everything with `pygame-gui` same error https://github.com/meanwhiletothestars/CS2_DMA_Radar/issues/48#issuecomment-2115456184

**Comment by elainakawai** [comment]
It didn't work at first. I deleted pygame and pygame_gui document. Then I installed them manually and it worked again.

**Comment by Suspectxyzz** [comment]
> It didn't work at first. I deleted pygame and pygame_gui document. Then I installed them manually and it worked again.

thanks for the info it works <3 love you

**Comment by pxkll** [comment]
i'm also getting same error on windows and wsl
