### ISSUE TITLE
can u updata

### ISSUE THREAD

**Issue by Esingpawn** [meanwhiletothestars/CS2_DMA_Radar#5]
struct ClientDLL {
    dwEntityList: 0x18B0FB8,
    dwGameRules: 0x190DF90,
    dwGlobalVars: 0x1719E30,
    dwLocalPlayerController: 0x1900918,
    dwLocalPlayerPawn: 0x17262D8,
    dwPlantedC4: 0x19161B8,
 
    // I do not use them
    dwForceForward: 0x171F390,  // thanks a2x for signature
    dwForceJump: 0x171F660,     // thanks a2x for signature
    dwViewAngles: 0x191E0D0,
    dwViewMatrix: 0x19102A0,
}
 
struct Engine2DLL {
    dwBuildNumber: 0x512554,
}
 
struct InputSystemDLL {
    dwInputSystem: 0x367A0,
}
 
struct CBasePlayerPawn {
    m_pWeaponServices: 0x1100,
    m_pItemServices: 0x1108,
    m_vOldOrigin: 0x127C,
    m_pClippingWeapon: 0x1308,
    m_bIsScoped: 0x1400,
    m_bIsDefusing: 0x1408,
    m_bIsGrabbingHostage: 0x1409,
    m_iShotsFired: 0x147C,
    m_flFlashDuration: 0x14CC,
    m_ArmorValue: 0x1570,
    m_angEyeAngles: 0x1578,
    m_iIDEntIndex: 0x15A4,
    m_aimPunchCache: 0x17A0,
}
 
struct CBaseEntity {
    m_pGameSceneNode: 0x318,
    m_iItemDefinitionIndex: 0x1BA,
    m_Item: 0x50,
    m_iTeamNum: 0x3CB,
    m_iHealth: 0x334,
    m_lifeState: 0x338,
    m_hPawn: 0x604,
    m_hPlayerPawn: 0x7E4,
    m_AttributeManager: 0x1098,
    m_iszPlayerName: 0x638,    
}
 
struct CItemServices {
    m_bHasDefuser: 0x40,
    m_bHasHelmet: 0x41,
}
 
struct CCSGameRules {
    m_bFreezePeriod: 0x30,
    m_bWarmupPeriod: 0x31,
    m_bHasMatchStarted: 0xA4,
    m_bBombPlanted: 0x9DD,
}
 
struct CPlantedC4 {
    m_nBombSite: 0xEDC,
    m_flC4Blow: 0xF08,
}
[Github SDK](https://github.com/NotOfficer/cs2-sdk/)

[[cs2go] - External ESP](https://www.unknowncheats.me/forum/counter-strike-2-releases/605464-cs2go-external-esp.html)
Code:
{
    "dwViewMatrix": 26280608,
    "dwLocalPlayerPawn": 24273624,
    "dwEntityList": 25890744,
    "m_hPlayerPawn": 2020,
    "m_iHealth": 820,
    "m_lifeState": 824,
    "m_iTeamNum": 971,
    "m_vOldOrigin": 4732,
    "m_pGameSceneNode": 792,
    "m_modelState": 352,
    "m_boneArray": 128,
    "m_nodeToWorld": 16,
    "m_sSanitizedPlayerName": 1864
}
[CS2 external esp](https://www.unknowncheats.me/forum/counter-strike-2-releases/600259-cs2-external-esp.html)
Code:
{
    "build_number": 13988,
    "dwEntityList": 25890744,
    "dwLocalPlayerController": 26216728,
    "dwLocalPlayer": 26216728,
    "dwViewMatrix": 26280608,
    "dwBuildNumber": 5317972,
    "dwPlantedC4": 26304952,
    "m_flC4Blow": 3848,
    "m_flNextBeep": 3844,
    "m_flTimerLength": 3856,
    "m_pInGameMoneyServices": 1784,
    "m_iAccount": 64,
    "m_vecAbsOrigin": 200,
    "m_pGameSceneNode": 792,
    "m_flFlashOverlayAlpha": 5312,
    "m_bIsDefusing": 5128,
    "m_szName": 3104,
    "m_pClippingWeapon": 4872,
    "m_ArmorValue": 5488,
    "m_iHealth": 820,
    "m_hPlayerPawn": 2020,
    "m_sSanitizedPlayerName": 1864,
    "m_iTeamNum": 971,
    "m_vecOrigin": 4732
}
Daived version:
Code:
{
    "dwEntityList": 25890744,
    "dwLocalPlayer": 26216728,
    "dwViewMatrix": 26280608,
    "dwPawnHealth": 2032,
    "dwPlayerPawn": 2020,
    "dwSanitizedName": 1864,
    "m_bIsLocalPlayerController": 1736,
    "m_iHealth": 820,
    "m_iTeamNum": 971,
    "m_vOldOrigin": 4732
}

**Comment by therewillwhile** [comment]
yes, there was 2 updates in a row so i wait a bit

**Comment by therewillwhile** [comment]
updated

**Comment by blondedye** [comment]
hello, i did update offsets manually after last night's but they're not working, can u help pls? thanks
