### ISSUE TITLE
GamersClub dont work

### ISSUE THREAD

**Issue by dontworkgrpc** [meanwhiletothestars/CS2_DMA_Radar#50]
After a few days using it to test your project, gamersclub updated its anti cheat and now I only see my team on the radar! Do you know what gamersclub did?

Is there a possibility for you to correct it?

Remembering that the official servers are working normally, but when I open the gamersclub anti cheat I only see my team's information

**Comment by Suspectxyzz** [comment]
this project is not to bypass anti-cheat

**Comment by therewillwhile** [comment]
i think this is kind of server-side problem. increase max clients in config to 64 and try. if it will not be able to see enemy idk what is it

**Comment by therewillwhile** [comment]
any ac will not rewrite for example offset of enemy. so it can be 2 cases -
1. use better dma firmware that will bypass isolating memory
2. probably server-side protect
