### ISSUE TITLE
How to update map/radar.png if map updates?

### ISSUE THREAD

**Issue by yungchunw** [meanwhiletothestars/CS2_DMA_Radar#51]
I want to know how to update de_vertigo/radar.png on external version. Because CS2 update brings new Vertigo.

**Comment by therewillwhile** [comment]
if u have new radar image. send it here and i will do it

**Comment by lay4021** [comment]
I want to know why I get an error when I run it and it crashes
<img width="958" alt="微信图片_20240616235410" src="https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/172515142/a5088467-6936-480b-968d-29a7e9d4a1b4">

**Comment by Suspectxyzz** [comment]
![de_vertigo_lower_radar_psd](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/dd68f878-06d8-44e8-be07-fd213f4c6145)
![de_vertigo_radar_psd](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/e042ac61-f301-4923-b57b-9d569586023e)


1.de_vertigo_lower_radar_psd {

VTEX Version = 1
Width        = 1024
Height       = 1024
Depth        = 1
NonPow2W     = 0
NonPow2H     = 0
Reflectivity = ( 0.542273, 0.492654, 0.093784, 0.055480 )
NumMipLevels = 1
Picmip0Res   = 0
Format       = 2 (VTEX_FORMAT_DXT5)
Flags        = 0x00000008
             | 0x00000008 = VTEX_FLAG_NO_LOD
Extra Data   = 2 entries:
               [ Entry 0: VTEX_EXTRA_DATA_FALLBACK_BITS - 1024 bytes ]
               [ Entry 1: VTEX_EXTRA_DATA_COMPRESSED_MIP_SIZE - 12 bytes ]
                   [ 1 mips, sized: 138050 ]
Mip level 0 - buffer size: 1048576

}

2.de_vertigo_radar_psd {

VTEX Version = 1
Width        = 1024
Height       = 1024
Depth        = 1
NonPow2W     = 0
NonPow2H     = 0
Reflectivity = ( 0.113596, 0.103390, 0.070031, 0.324960 )
NumMipLevels = 1
Picmip0Res   = 0
Format       = 28 (VTEX_FORMAT_BGRA8888)
Flags        = 0x00000008
             | 0x00000008 = VTEX_FLAG_NO_LOD
Extra Data   = 2 entries:
               [ Entry 0: VTEX_EXTRA_DATA_FALLBACK_BITS - 1024 bytes ]
               [ Entry 1: VTEX_EXTRA_DATA_COMPRESSED_MIP_SIZE - 12 bytes ]
                   [ 1 mips, sized: 107970 ]
Mip level 0 - buffer size: 4194304


}


@meanwhiletothestars

**Comment by therewillwhile** [comment]
need simpleradar style like previous

**Comment by Suspectxyzz** [comment]
@meanwhiletothestars 
![de_vertigo_lower_radar_spectate](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/085cf7bf-b36e-4f4e-9ebd-2ec5aa7f619f)
![de_vertigo_radar_spectate](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/a555c398-efbd-4cd3-9d54-b7ec308e1215)

**Comment by therewillwhile** [comment]
need to make picture like this ---> https://github.com/meanwhiletothestars/CS2_DMA_Radar/blob/DMA/maps/de_vertigo/radar.png

**Comment by therewillwhile** [comment]
https://github.com/meanwhiletothestars/CS2_DMA_Radar/blob/DMA/maps/de_vertigo/radar.png


**updated**
