### ISSUE TITLE
Crash and error report cannot be opened

### ISSUE THREAD

**Issue by lay4021** [meanwhiletothestars/CS2_DMA_Radar#54]
I want to know why I get an error when I run it and it crashes
<img width="958" alt="微信图片_20240616235410" src="https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/172515142/fe692727-e34b-474d-b149-8a3066e311cb">

**Comment by therewillwhile** [comment]
no internet connection. if u want to use without internet ----> ur offsets.json and client.json should be up to date
