### ISSUE TITLE
Doesnt work after update

### ISSUE THREAD

**Issue by boomurino** [meanwhiletothestars/CS2_DMA_Radar#57]
![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/174649140/01a6b21f-c448-4c11-a817-7b477e28bc34)
can you help me please?

**Comment by therewillwhile** [comment]
это в какой версии? dma?

**Comment by boomurino** [comment]
> это в какой версии? dma?

dma

**Comment by therewillwhile** [comment]
исправил в архиве https://github.com/meanwhiletothestars/CS2_DMA_Radar/releases/download/1.7/DMA.zip

**Comment by boomurino** [comment]
братик целую тебя в попу

**Comment by boomurino** [comment]
на тонкоин отправлял на шаву тебе

**Comment by boomurino** [comment]
![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/174649140/96ca361e-8c11-416d-9dcd-0d3359a12385)
