### ISSUE TITLE
один хрен ошибка бро

### ISSUE THREAD

**Issue by boomurino** [meanwhiletothestars/CS2_DMA_Radar#58]
![image](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/174649140/76bdc6cb-5fc7-4cba-93f7-4d90c39bfb53)
(дма версия)

**Comment by therewillwhile** [comment]
залил новый, щас должно работать. просто нет возможности протестить сейчас

**Comment by boomurino** [comment]
заработало
