### ISSUE TITLE
Issue with Vmm.init()

### ISSUE THREAD

**Issue by egorchecpc** [meanwhiletothestars/CS2_DMA_Radar#61]
I get this errors, gpt tell me die (
Help please some1

Traceback (most recent call last):
  File "C:\cs2_radar\app.py", line 230, in <module>
    vmm = memprocfs.Vmm(['-device', 'fpga', '-disable-python', '-disable-symbols', '-disable-symbolserver', '-disable-yara', '-disable-yara-builtin', '-debug-pte-quality-threshold', '64'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Vmm.init(): Initialization of vmm failed.

I think it has to do with the fact that I have an AMD processor

**Comment by therewillwhile** [comment]
disable iommu

**Comment by therewillwhile** [comment]
u can ask any question and get help in our discord
