### ISSUE TITLE
mapname address

### ISSUE THREAD

**Issue by AirJM** [meanwhiletothestars/CS2_DMA_Radar#62]
Excuse me, how did you determine that the offset 0x1B8 in the address dwGlobalVarsvar + 0x1B8 is for reading the map name? I couldn't find the relevant offset in client_dll.json. In your testing/offset_manipulator.py, I found the method to get the map name from matchmaking.dll, but I couldn't find the 0x1B8 offset from client_dll.

By the way, this is a great project!

**Comment by Suspectxyzz** [comment]
https://github.com/a2x/cs2-dumper/tree/main/output
ask to add  dwGlobalVarsvar

**Comment by therewillwhile** [comment]
0x1B8 is hardcoded offset, because it didnt change across updates. getting from matchmaking.dll is outdated
