### ISSUE TITLE
maps no de_dust2

### ISSUE THREAD

**Issue by HH333** [meanwhiletothestars/CS2_DMA_Radar#7]
maps no de_dust2    ，How to addde_dust2

**Comment by Suspectxyzz** [comment]
![radar](https://github.com/meanwhiletothestars/CS2_DMA_Radar/assets/45514952/9795e608-f677-47fc-bf5c-671a44937545)
[meta.json](https://github.com/meanwhiletothestars/CS2_DMA_Radar/files/14224179/meta.json)
make a folder de_dust2

**Comment by mn2xujiakun** [comment]
> ![radar](https://private-user-images.githubusercontent.com/45514952/303717611-9795e608-f677-47fc-bf5c-671a44937545.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NDU2ODIsIm5iZiI6MTcwNzU0NTM4MiwicGF0aCI6Ii80NTUxNDk1Mi8zMDM3MTc2MTEtOTc5NWU2MDgtZjY3Ny00N2ZjLWJmNWMtNjcxYTQ0OTM3NTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA2MDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MTczMTQ1OWU1YmJiZWM3ZmYxOTE0MTdiNTFiNmI2ZDlkZjU1MTUxN2JiYzM3YWQ3MTk1NTRhYTU1MmMwNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pnRuEXfazJ50l8pSGHZxhXxqbTpac_cmgSmwBgAWhWk) [meta.json](https://github.com/meanwhiletothestars/CS2_DMA_Radar/files/14224179/meta.json) make a folder de_dust2

Thank you so much for providing the map and offsets, I am wondering how to get the offset of map, just in case that I want to add other maps

**Comment by therewillwhile** [comment]
> > ![radar](https://private-user-images.githubusercontent.com/45514952/303717611-9795e608-f677-47fc-bf5c-671a44937545.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NDU2ODIsIm5iZiI6MTcwNzU0NTM4MiwicGF0aCI6Ii80NTUxNDk1Mi8zMDM3MTc2MTEtOTc5NWU2MDgtZjY3Ny00N2ZjLWJmNWMtNjcxYTQ0OTM3NTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA2MDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MTczMTQ1OWU1YmJiZWM3ZmYxOTE0MTdiNTFiNmI2ZDlkZjU1MTUxN2JiYzM3YWQ3MTk1NTRhYTU1MmMwNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pnRuEXfazJ50l8pSGHZxhXxqbTpac_cmgSmwBgAWhWk) [meta.json](https://github.com/meanwhiletothestars/CS2_DMA_Radar/files/14224179/meta.json) make a folder de_dust2
> 
> Thank you so much for providing the map and offsets, I am wondering how to get the offset of map, just in case that I want to add other maps

/testing offsetfinder.py u can use it for find offset for any map
